CREATE OR REPLACE TRIGGER TDeleteGameEvent BEFORE DELETE ON GAME_PLAYS
FOR EACH ROW
DECLARE
    v_home_team_id INT;
BEGIN

    SELECT HOME_TEAM_ID INTO v_home_team_id FROM GAME WHERE GAME_ID = :OLD.GAME_ID;

    IF :OLD.EVENT = 'GOAL' THEN
        IF :OLD.TEAM_ID_FOR = v_home_team_id THEN
            UPDATE GAME 
            SET HOME_GOALS = HOME_GOALS - 1 
            WHERE GAME_ID = :OLD.GAME_ID;
            
            UPDATE GAME_TEAMS_STATS 
            SET GOALS = GOALS - 1
            WHERE GAME_ID = :OLD.GAME_ID AND TEAM_ID = :OLD.TEAM_ID_FOR;
        ELSE
            UPDATE GAME 
            SET AWAY_GOALS = AWAY_GOALS - 1
            WHERE GAME_ID = :OLD.GAME_ID;
           
            UPDATE GAME_TEAMS_STATS
            SET GOALS = GOALS - 1
            WHERE GAME_ID = :OLD.GAME_ID AND TEAM_ID = :OLD.TEAM_ID_FOR;
        END IF;
    
    ELSIF :OLD.EVENT = 'Shot' THEN
        UPDATE GAME_TEAMS_STATS 
        SET SHOTS = SHOTS - 1
        WHERE GAME_ID = :OLD.GAME_ID AND TEAM_ID = :OLD.TEAM_ID_FOR;
    END IF;
END;
